project_name: cf-routing-suite
builds:
  -
    main: ./server/.
    binary: cfrs-server
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
    - amd64
  -
    main: ./client/.
    binary: cfrs-client
    ldflags: -s -w -X main.version={{.Version}}
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
archive:
  wrap_in_directory: true
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  files:
  - README.md
  - LICENSE
  - server/static/*
  - server/static/html/*
  - server/static/stylesheets/*


checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

release:
  draft: false
  github:
    owner: sklevenz
    name: cf-routing-suite

brew:
  folder: Formula
  homepage: "https://github.com/sklevenz/cf-routing-suite/"
  description: "A suite containing (server) and client for challenging the cloud foundry routing tier."
  test: |
    system "#{bin}/cf-routing-suite/client/cfrs-client -version"
    system "#{bin}/cf-routing-suite/server/cfrs-server -version"
  install: |
    bin.install "cfrs-client"
    bin.install "cfrs-server"
  github:
    owner: sklevenz
    name: hombrew-skl
