#!/usr/bin/env bash

rm -f ./cfrs-server/cfrs-server
go test ./cfrs-server/...
go build -o ./cfrs-server/cfrs-server ./cfrs-server/...
./cfrs-server/cfrs-server version

rm -f ./cfrs-server/cfrs-client
go test ./cfrs-client/...
go build -o ./cfrs-client/cfrs-client ./cfrs-client/...
./cfrs-client/cfrs-client version
